### ISSUE TITLE
Poll companies for Graphite Case Studies

### ISSUE THREAD

**Issue by gwaldo** [graphite-project/graphite-project.github.io#11]
Reach out to companies for use cases, lessons-learned, scaling issues, war stories, etc.

Possible sources:
* [Etsy](http://codeascraft.com/)
* [Jawbone](https://github.com/graphite-project/carbon/issues/45)
* more?

**Comment by obfuscurity** [comment]
Here are a number of case studies that I collected for the Graphite Book. We should get approval to include them on the website if we choose to go that route.

https://gist.github.com/obfuscurity/d37ed1d46d6b311c437d/forks

**Comment by obfuscurity** [comment]
Props to @mrtazz @afelle1 @whilp @jssjr @reyjrar for their contributions there.

**Comment by obfuscurity** [comment]
Per @kjoconnor, Reddit uses Graphite:
https://twitter.com/gooeyblob/status/662493037294018560

@standaloneSA has also mentioned that SpaceX uses Graphite.

Do we have your permission to mention this on the new website?

**Comment by obfuscurity** [comment]
@skeller047 is it still accurate that EA is using Graphite? For some reason I have this weird recollection that you might have moved off to something else.

**Comment by skeller047** [comment]
@obfuscurity yes EA is still using Graphite.  We have evaluated some alternatives, but no conclusions as of yet.

**Comment by kjoconnor** [comment]
Permission granted! Thanks!

**Comment by standaloneSA** [comment]
I can't speak for SpaceX at all or any technologies we use or don't. Sorry,

Matt

**Comment by obfuscurity** [comment]
@standaloneSA that's a bummer.

**Comment by mrtazz** [comment]
@obfuscurity sorry this totally slipped my radar. I'll double check about putting that information on a public website.

**Comment by obfuscurity** [comment]
We've shipped the case studies and company logos to the website. If you'd like to see your company added, by all means please let me know.
