### ISSUE TITLE
Port wikidot Carbon page to Docs

### ISSUE THREAD

**Issue by gwaldo** [graphite-project/graphite-project.github.io#12]
http://graphite.wikidot.com/carbon

Refs https://github.com/graphite-project/graphite-project.github.io/issues/4
Descended from https://github.com/graphite-project/graphite-project.github.io/issues/6

**Comment by obfuscurity** [comment]
Going to merge any missing bits into http://graphite.readthedocs.io/en/latest/carbon-daemons.html.
