### ISSUE TITLE
Port wikidot Whisper page to Docs

### ISSUE THREAD

**Issue by gwaldo** [graphite-project/graphite-project.github.io#13]
http://graphite.wikidot.com/whisper

Refs https://github.com/graphite-project/graphite-project.github.io/issues/4
Descended from https://github.com/graphite-project/graphite-project.github.io/issues/6

**Comment by obfuscurity** [comment]
Going to merge any missing bits into http://graphite.readthedocs.io/en/latest/whisper.html.

**Comment by obfuscurity** [comment]
Turns out that the existing Whisper file covers all the information in the old wikidot page.
