### ISSUE TITLE
Repository sub-title should note that http://graphite-project.github.io/ is not live yet

### ISSUE THREAD

**Issue by ryan-williams** [graphite-project/graphite-project.github.io#15]
It currently reads "Website for the Graphite project http://graphite-project.github.io", which is confusing because that URL 404s.

Some explanation that the site is under construction and will be live at that URL soon would be less confusing; additionally, a note about the best place to find documentation in the meantime (readthedocs.org?) might make sense in the README.

**Comment by esc** [comment]
perhaps we should repoen: https://github.com/graphite-project/graphite-project.github.io/issues/15

**Comment by ryan-williams** [comment]
nice, thanks!
