### ISSUE TITLE
Some minor nits

### ISSUE THREAD

**Issue by obfuscurity** [graphite-project/graphite-project.github.io#26]
A handful of layout issues I noticed that might be nice to tweak before we go GA. Many of these are pixel-offset issues that most people wouldn't notice but annoy the bejeezus out of me. 😺

* header links misaligned when scrolling
* hexagonal bullets, numbers not centered
* partial borders around some buttons
* vertical alignment on integration logos (not a bug, but needs adjusting)
* footer layout (unsure if this is a bug or intentional but it looks weird to me)

/cc @bulletfactory

**Comment by bulletfactory** [comment]
Thanks for putting this list together- we'll tackle these items when we arrive in PDX

T

**Comment by bulletfactory** [comment]
- [ ] header links misaligned when scrolling
- [x] hexagonal bullets, numbers not centered
- [x] partial borders around some buttons
- [x] vertical alignment on integration logos (not a bug, but needs adjusting)
- [ ] footer layout (unsure if this is a bug or intentional but it looks weird to me)
