### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by obfuscurity** [graphite-project/graphite-project.github.io#3]
I'd like to resume work on this Pages site that was introduced by @mleinart a couple years ago. I envision this as something similar to the [new Sensu site](http://sensuapp.org/), which is beautifully done in both design and simplicity.

I have registered the graphiteapp.org domain, which I think would be suitable for the project. This can be CNAME'd to the GitHub Pages name (graphite-project.github.io).

All of our current project documentation (i.e. content found at http://graphite.readthedocs.org/) should be linked directly from this site. It should be easy to find, and each version should be linked independently.

There should be support information available on the site, including:

* link to [Launchpad Answers](https://answers.launchpad.net/graphite/)
* link(s) to the documentation
* irc channel details
* mailing list details (assuming we wish to continue using this in *addition to* LP answers)

If there are any other requirements for the *new site*, please include them below. There will be a separate issue for decommissioning the old [wikidot site](http://graphite.wikidot.com/) and tracking any dependencies for that task (e.g. filling in missing content at RTD), so let's focus only on the new site here.

/cc @graphite-project/committers

**Comment by obfuscurity** [comment]
FWIW I'm finally digging into the new website. I have the basic wireframes for the SPA home page and am coding the bits as we speak.

**Comment by SEJeff** [comment]
Any specific tech you're using? For SPA, I really dig react and found that angular seems to make things harder for no great reason.

**Comment by obfuscurity** [comment]
Sorry, I made that sound way more exciting than it really is. It's mostly going to be static with maybe a little JS thrown in just to manage customer stories and tools. It's all hosted on GitHub Pages and there are no (planned) external calls.

**Comment by SEJeff** [comment]
Static html? Sounds very web scale. How does it get those kickass benchmarks?

**Comment by obfuscurity** [comment]
I'm not even sure where the real questions ended and the trolling began.

**Comment by bulletfactory** [comment]
Quick Shopping List:

Features Section
 - Overview explaining what Graphite is

- Official documentation will live on raeadthedocs.org

Quickstart for getting metrics in
Quickstart for getting metrics out

- Quickstart Guide for installation
   - synthesize


- Something similar to play.grafana.org?

Customer Stories
 - Use Cases

Download

Support details
- read the docs
- launchpad answers
- irc
- github projects

Integrations Gallery
 - http://graphite.readthedocs.org/en/latest/tools.html

![overview](https://cloud.githubusercontent.com/assets/1950595/10984139/752af524-83e5-11e5-98e4-073f689a3e63.png)

**Comment by bulletfactory** [comment]
Initial Page Load
![graphite_homepage_001a](https://cloud.githubusercontent.com/assets/1950595/11158187/88796616-8a24-11e5-91c5-ec35f026c9d0.png)

Scrolling Down the Site
![graphite_homepage_001a_scroll_1](https://cloud.githubusercontent.com/assets/1950595/11158191/909c84ea-8a24-11e5-9187-fabb807b29ef.png)

Case Studies Page Concept
![Uploading graphite_case_studies_001a.png…]()

**Comment by JeanFred** [comment]
Wow, these are pretty cool mockups @bulletfactory!

**Comment by deniszh** [comment]
:+1: 
IMO we could leave motto as is - "Graphite. Kicks ass. Chew bubblegum." :D

**Comment by bulletfactory** [comment]
I took some time to update the mockup. The current version felt a little too mechanical and read more like a white-paper than a website. I wanted to re-examine the color palette, and shuffle the sections around some. I thought some bigger blocks of color might help it feel less dry. Open to using different colors, but wanted to illustrate what large gradient block might look like. I wasn't convinced that the type needed rethinking at this point, but if this still doesn't hit the feeling we're going for, I'm more than happy to swap out the type for headlines at the very least.

Added:
Case study buttons on various logos (need to identify which companies/users to highlight)
Quickstart Guide buttons w/ link to other guides
Integrations Section with logos (need to identify which integrations to highlight)
Larger CTAs to launchpad and docs.

I think we're close, but am looking for feedback. How does this feel? Are we closer or further away from the vision?

![graphite_homepage_002a](https://cloud.githubusercontent.com/assets/1950595/11280248/15903ece-8ec3-11e5-829a-64396a245894.png)

**Comment by drawks** [comment]
Bad Ass :+1:

**Comment by obfuscurity** [comment]
That looks amazing. I love the color treatment in the logo and the backgrounds. The only nit (and an easy fix) would be the spacing in the arch section, but I acknowledge this is just a mockup.

**Comment by torkelo** [comment]
@bulletfactory looks great!

**Comment by mattttt** [comment]
@bulletfactory Really liking this. I think there's a good opportunity to animate the paths on the hero image using Vivus: https://maxwellito.github.io/vivus/ 

Just a bit of motion in the background, on pageload, but not so much that it's annoying. Further, only on the first one - not the rest (it'd get super annoying).

**Comment by pyr** [comment]
@bulletfactory awesome work

**Comment by bitprophet** [comment]
@bulletfactory Flippin' awesome!

**Comment by deniszh** [comment]
Very cool! Love that hexagonal themes everywhere. :+1:

**Comment by obfuscurity** [comment]
https://github.com/graphite-project/graphite-project.github.io/pull/16

**Comment by obfuscurity** [comment]
Marking this complete. There are still some items left to ship but we're tracking them as separate issues. If there's something I've missed please let me know.
