### ISSUE TITLE
Markdown not rendered on some templates

### ISSUE THREAD

**Issue by kylechadha** [graphite-project/graphite-project.github.io#32]
Just thought I'd pass this along, noticed markdown is not being rendered on https://graphiteapp.org/quick-start-guides/synthesize.html

`If you're a [DigitalOcean](https://www.digitalocean.com/) customer, deploying Graphite is literally as easy as clicking the **Install on DigitalOcean** button below. You'll have the option to change the default instance size (512MB) or region (New York 3). For most users the default are fine. Accept the terms and click the **big green button** to launch your own Graphite instance.`

**Comment by obfuscurity** [comment]
Good catch, thanks!
